stage 1: added page contacts and activities
Mihail-tec/webix-jet-app pull request #1
Opened 2022-04-25 07:54 UTC by Mihail-tec

2022-04-25 08:17 UTC, AlexeyXB requested changes

2022-04-25 08:17 UTC, AlexeyXB commented on sources/views/top.js
> +		menu.attachEvent("onAfterSelect", () => {
Лучше события добавлять через `on`

2022-04-25 08:17 UTC, AlexeyXB commented on sources/views/popup.js
> +		const form = this.$$("form");
Почему бы в таком случае не сделать в `init` переменную `this.form`

2022-04-25 08:17 UTC, AlexeyXB commented on sources/views/popup.js
> +		this.$$("addClick").setValue("Save");
Также лучше сделать переменную для `this.$$("addClick")`

2022-04-25 08:17 UTC, AlexeyXB commented on sources/views/contacts.js
> +			this.on(this.list, "onAfterSelect", (id) => {
Почему бы не добавить это в уже существующий `onAfterSelect`?

2022-04-25 08:17 UTC, AlexeyXB commented on sources/views/contacts.js
> +			this.$$("infoTitle").parse(contact);
`infoTitle` и `infoMain` можно вынести в `this.infoTitle` и `this.infoMain`

2022-04-25 08:17 UTC, AlexeyXB commented on sources/views/activities.js
> +						return false;
Для чего тут `return false`?

2022-04-25 10:07 UTC, AlexeyXB requested changes

2022-04-25 10:07 UTC, AlexeyXB commented on sources/views/activities.js
> +		this.$$("datatable").parse(activities);
`this.$$("datatable")` -> `this.table`

2022-04-25 11:20 UTC, kullias requested changes

2022-04-25 11:20 UTC, kullias commented on sources/views/activities.js
> +								const dateCell = webix.Date.dayStart(cell).getTime();
в вебиксе есть webix.Date.equal, если что

2022-04-25 11:20 UTC, kullias commented on sources/views/activities.js
> +						const getId = this.$$("datatable").getItem(id);
getId плохое имя для константы, которая хранит объект (это хорошее имя для метода)
лучше obj, data или что-то такое

2022-04-25 11:20 UTC, kullias commented on sources/views/activities.js
> +				data: activities,
данные сеттятся тут и ниже через parse
я лично за то чтобы остался parse
лучше отделяет построение интерфейса от работы с данными

2022-04-25 11:20 UTC, kullias commented on sources/views/activities.js
> +						this.show(`/top/activities?id=${id}`);
чисто для смены параметра урла наверное лучше setParam("id", id, true)

2022-04-25 11:20 UTC, kullias commented on sources/views/activitiesPopup.js
> +import Popup from "./popup";
логичнее назвать это формой

2022-04-25 11:20 UTC, kullias commented on sources/views/popup.js
> +					invalidMessage: "Filed required"
наверное опечаточка в message
filed?

2022-04-25 11:20 UTC, kullias commented on sources/views/popup.js
> +				TypeID: webix.rules.isNotEmpty,
в принципе и сам required пустые значения не пропустит https://snippet.webix.com/crjx917v

2022-04-25 11:20 UTC, kullias commented on sources/views/popup.js
> +		this.form.clearValidation();
раз на выходе зачищается, тут уже вроде не надо

2022-04-25 11:20 UTC, kullias commented on sources/views/contacts.js
> +			this.show(`/top/contacts?id=${id}`);
при переключении не все данные ресетятся (вероятно дело в моей базе, в которой есть пустые поля)
где данных нет светится undefined - думаю стоит добавить тут какую-то заглушку типа `(no skype)`
![Peek 2022-04-25 14-09](https://user-images.githubusercontent.com/31205423/165077678-89f35590-089b-4aaf-9164-4fe292dfebd5.gif)

2022-04-25 11:20 UTC, kullias commented on sources/views/contacts.js
> +			this.show(`/top/contacts?id=${id}`);
![Selection_999(819)](https://user-images.githubusercontent.com/31205423/165077786-6bc4df8d-6c9b-478b-90f8-7f6a8c865987.png)

2022-04-25 11:20 UTC, kullias commented on sources/views/activities.js
> +						id: "DueDate",
вероятно потому что тут строковое поле сортировка как-то странно работает
каждый второй клик ничего не делает

2022-04-25 13:45 UTC, AlexeyXB approved these changes

2022-04-26 08:52 UTC, kullias commented on sources/views/contacts.js
> +			this.show(`/top/contacts?id=${id}`);
данные при переключении все так же не меняются чаще всего (могу скинуть свой файл с базой для тестирования)

2022-04-26 08:56 UTC, kullias commented on sources/views/activities.js
> +						id: "DueDate",
а теперь даты уходят в неправильном формате, и бэкенд их зануляет
![Selection_999(840)](https://user-images.githubusercontent.com/31205423/165262605-3d873807-0aac-4a2a-a01a-1ad04e54fe43.png)

![Selection_999(839)](https://user-images.githubusercontent.com/31205423/165262282-7ed026be-5fc7-4b32-823c-0af98e290240.png)

поскольку ты заменяешь значение в самом DueDate, перед отправкой нужно их привести в правильный вид
у дата процессора есть событие onBeforeSend

2022-04-26 11:34 UTC, kullias approved these changes

2022-04-26 11:35 UTC, merged