stage 2: realesed page contacts with information
Mihail-tec/webix-jet-app pull request #2
Opened 2022-05-04 12:14 UTC by Mihail-tec

2022-05-04 13:08 UTC, AlexeyXB requested changes

2022-05-04 13:08 UTC, AlexeyXB commented on sources/views/activitiesPopup.js
> +		if (id) {
Так как тут ты проверяешь наличие id, то все что ниже будет работать для существующего id. Т.е. код не совсем корректен. Судя по этой логике у addClick не будет 'Add', а у header - 'Add activity'

2022-05-04 13:08 UTC, AlexeyXB commented on sources/views/activitiesTable.js
> +				details.data.DueDate = webix.Date.dateToStr("%Y-%m-%d %H:%i")(details.data.DueDate);
Я думаю, лучше эту часть вынести в `scheme` в коллекцию `activities`.

2022-05-04 13:08 UTC, AlexeyXB commented on sources/views/contacts/contactForm.js
> +				if (contact) {
Т.е. сперва ты проверяешь на наличие контакта, сетишь значения, а потом снова сетишь такие же значение, но уже без проверки. Вопрос - нужна ли тогда тут проверка на существование контакта? Если нужна, то нужно что-то делать, когда контакта не существует.

2022-05-04 13:08 UTC, AlexeyXB commented on sources/views/contacts/info.js
> +	Info() {
Не самое лучше имя для функции. Это имя не говорит нам ничего  о том, что эта функция делает. Тем более что все функции у тебя с маленькой буквы начинаются, а тут большая.

2022-05-05 08:01 UTC, AlexeyXB commented
В форме для редактирования контакта я могу ввести двусоставное имя, но это имя не пройдет валидацию

2022-05-05 08:03 UTC, AlexeyXB commented
После нажатия на кнопку 'Save' при редактировании существующего контакта, очищается форма, а по заданию я должен попасть на страницу с описанием отредактированного пользователя.

2022-05-05 08:03 UTC, AlexeyXB commented
Сообщение в confirm перед удалением стоит расширить, чтобы я понимал в чем конкретно я уверен.

2022-05-05 08:04 UTC, AlexeyXB commented
При удалении контакта должны удаляться и Активити этого контакта. У тебя же после удаления Активити остаются.

2022-05-05 08:05 UTC, AlexeyXB commented
При добавлении Активити на странице контактов я не должен иметь возможности менять contact в форме добавления activity.

2022-05-05 08:05 UTC, AlexeyXB commented
Не хвататет обработки ошибок при загрузке файлов

2022-05-05 08:06 UTC, AlexeyXB commented
Сортировка по change date у файлов не работет.

2022-05-05 11:25 UTC, kullias commented
на маленьких экранах с открытым дев тулз печаль
![Screenshot from 2022-05-05 14-24-39](https://user-images.githubusercontent.com/31205423/166913815-6407e6e3-ad28-46f1-8eb1-12f6f6a6504f.png)

2022-05-05 11:31 UTC, kullias commented
> В форме для редактирования контакта я могу ввести двусоставное имя, но это имя не пройдет валидацию

у меня и какой-то произвольный текст не проходит
![Screenshot from 2022-05-05 14-28-46](https://user-images.githubusercontent.com/31205423/166914654-4f7e8588-570f-4371-9eb9-00d09e383b18.png)

2022-05-05 11:46 UTC, kullias commented
надо выровнять ширину лейблов, чтоб не было такой лесенки
![Screenshot from 2022-05-05 14-45-19](https://user-images.githubusercontent.com/31205423/166916793-a59ac64f-61ee-448a-bd78-b2388f4b695b.png)

2022-05-05 11:56 UTC, kullias commented
> Сообщение в confirm перед удалением стоит расширить, чтобы я понимал в чем конкретно я уверен.

мне кажется на удаление фотки конфирм не очень надо, поскольку чел может всей форме нажать cancel и все дела
а вот конфирм всей форме на такое нужнее (поредактировали, потом нажали cancel, и вероятно надо уточнить, точно ли чел задумал потерять наредактированное

2022-05-05 14:42 UTC, kullias requested changes

2022-05-05 14:42 UTC, kullias commented on sources/views/activitiesTable.js
> +		this.contactId = this.getParam("contactsId", true);
после инита срабатывает urlChange , потому из инита можно спокойно убирать фильтрацю по контакту

2022-05-05 14:42 UTC, kullias commented on sources/views/contacts/contactDetails.js
> +				this.window.showWindow(this.id);
поскольку this.id это параметр урла, он доступен и внутри окна, так что вообще можно и не передавать, а там взять
он будет там доступен потому что у окон, которые созданы через this.ui, и у статических сабвью нет своего сегмента урла и все параметры сеттятся в сегмент родителя и потому доступны им как свои (а родительские параметры их родителя - т.е. параметры дедушки - как их родительские)

2022-05-05 14:42 UTC, kullias commented on sources/views/contacts/contactForm.js
> +					const valid = /^[A-ЯЁ][а-яё]{2,20}|[A-Z][a-z]{2,20}$/.test(value);
return /.../.test(value);
или
return valid;

2022-05-05 14:42 UTC, kullias commented on sources/views/contacts/contactForm.js
> +		if (this.id) {
не баг, но скорее идеологический момент:

this.id сеттится только в ините, значит только раз за жизнь этой вьюшки
урл чейндж теоретически может срабатывать много раз за жизнь вьюшки, но не здесь, потому что тут при изменениях в урле форма уничтожается. 
а если бы и срабатывал много раз, то делалось бы каждый раз одно и то же, поскольку this.id не менялась бы
насколько я вижу, нету смысла это все делать в урл чейндже, можно вынести в инит

2022-05-05 14:42 UTC, kullias commented on sources/views/contacts/contactForm.js
> +			if (contacts.exists(formValues.id)) {
у нового контакта кажется formValues.id будет undefined всегда

2022-05-05 14:42 UTC, kullias commented on sources/views/contacts/contactForm.js
> +			this.form.clear();
поскольку после сохранения редактирования/добавления форма закроется и задестроится (по крайней мере так надо сделать при любом раскладе, когда редактирование окончено сохранением или отменой), можно не чистить. это окно живет себе дальше, а форма эта нет

2022-05-05 14:42 UTC, kullias commented on sources/views/contacts/index.js
> +					animate: false,
ты наверное тут забыл останки малтивью
оно не надо
кроме листа тут чисто `{$subview: true}` должно остаться

2022-05-05 14:42 UTC, kullias commented on sources/views/contacts/info.js
> +								this.show(`contacts.contactForm?id=${this.id}`);
поскольку айди контакта хранится в сегменте урла родителя, то она доступна и из формы будет, не надо передавать его ей отдельно
вот если бы айди хранилась у детей (у инфо, у формы) - другое дело

у тебя ситуация `/contacts?contactsId=1/info` и /contacts?contactsId=1/form`, и там и там эта айди доступна
а вот если б ситуация была /contacts/info?contactsId=1`, тогда да, у формы нету доступа к этой айди и надо ей его передать

2022-05-05 14:42 UTC, kullias commented on sources/views/contacts/info.js
> +		this.showDataContact();
у тебя этот метод вызывается на ините в любом случае, а потом если есть айди - вызывается еще и в урл чейндже
то есть вызывается по-любому при инициализации 2 раза, а потом уже по делу, потому что потом там есть айди
потом там внутри метода проверка на существование айтема по такому айди

в ините вызов не нужен, урл чейндж вызовется после него и все сделает

2022-05-05 14:42 UTC, kullias commented on sources/views/contacts/list.js
> +				this.show("contacts.contactForm");
не снимается селект с листа, остается айди старого контакта в урле

2022-05-05 14:42 UTC, kullias commented on sources/views/contacts/list.js
> +		this.show("");
а зачем?

2022-05-05 14:42 UTC, kullias commented on sources/views/contacts/list.js
> +			this.list.unselectAll();
дальше по-любому будет какой-то селект, если есть что селектить, так что не надо анселект (а если нечего, то проблема отпадает в принципе)

2022-05-05 14:42 UTC, kullias commented on sources/views/contacts/list.js
> +			this.list.unselectAll();
к слову о ситуации когда селектить уже нечего: данные последнего удаленного контакта все еще отображаются, что не очень хорошо, и удаление даже можно попытаться снова повторить
когда уже нечего селектить, хорошая идея как-то сбросить инфо, чтобы оно показывало что-то типа "Add a contact" или показать простую вьюшку на месте инфо с таким же содержанием (темплейт)

2022-05-05 14:42 UTC, kullias commented on sources/views/filesTable.js
> +					id: "changeDate",
а поле в объекте называется date
если айди не совпадает с тем, что показываешь, и поля такого нет, то стоит id:"" писать, а то невольно ищешь такое поле и нету
но вообще вероятно потому сортировка и не работает - она-то работает с полем по имени changeDate, если сортировщик не "text" и не кастомная функция

2022-05-06 08:47 UTC, kullias commented on sources/views/contacts/contactDetails.js
> +		this.id = this.getParam("id", true);
тут он всегда undefined, его можно убрать из кода этого вью вообще

2022-05-06 08:51 UTC, kullias commented on sources/views/contacts/list.js
> +			this.list.unselectAll();
поскольку селект не сработает в случае, когда в листе уже селектнут тот же айтем - оставляем. не учла этот кейс
примечание: более каноничный по джету способ возвращаться из инфо в форму - вызывать this.show 
но этот в принципе тоже норм - 1 коммент отбой

а вот для кейса когда селектить нечего действительно надо проверить, нормально ли инфо показывается (он не должен показывать старую инфу. в идеале - сообщение в духе "ничего нет, добавьте" (см 2 коммент выше)

2022-05-06 13:00 UTC, kullias commented on sources/views/filesTable.js
> +					try {
https://docs.webix.com/api__ui.uploader_onfileuploaderror_event.html
вот это Алексей имел в виду, я думаю
в коде тут нету ничего такого, что сломается и кинет ошибку
тут конечно нету реальной загрузки, но проект учебный, и это типа на будущее хорошая практика - добавить обработчик, который будет обрабатывать ошибки загрузки файлов

2022-05-06 13:02 UTC, AlexeyXB commented on sources/views/filesTable.js
> +					try {
Да, лучше воспользоваться onFileUploadError

2022-05-06 13:17 UTC, kullias commented
когда открывается инфо, у таббара не выставлено value, из-за чего ни один таб не селектнут

2022-05-06 13:21 UTC, kullias commented on sources/views/contacts/contactForm.js
> +						webix.confirm("All unsaved data will be lost, are you sure?")
стоит добавить проверку на dirty , потому что если ничего не менял в форме, странно видеть такой вопрос

2022-05-06 13:55 UTC, kullias approved these changes

2022-05-10 05:55 UTC, AlexeyXB approved these changes

2022-05-10 05:55 UTC, merged