stage 3: added locale with ru and end, added filter on contacts and a…
Mihail-tec/webix-jet-app pull request #3
Opened 2022-05-11 13:25 UTC by Mihail-tec

…dded tabbar in active table

2022-05-11 14:34 UTC, kullias commented on sources/views/activitiesTable.js
> +	changeTabbar(id) {
наверное название для метода попонятнее будет каким-то типа filterByTabbar

2022-05-11 14:34 UTC, kullias commented on sources/views/activitiesTable.js
> +						this.changeTabbar(this.tabbar.getValue());
мне кажется этот обработчик не надо, поскольку:
- onStoreUpdated вызывает filterByAll
- filterByAll вызывает событие onAfterFilter
- onAfterFIlter вызывает этот же метод

или там что-то ломается? (кажется не)

2022-05-11 14:34 UTC, kullias commented on sources/views/activitiesTable.js
> +						this.changeTabbar(id);
кажется этот вызов не надо при текущей огранизации всей этой фильтрации (см коммент пониже)
или таки что-то ломается? (кажется не)

2022-05-11 14:34 UTC, kullias commented on sources/views/contacts/list.js
> +		const value = this.filterContacts.getValue().toLowerCase().trim();
есть смысл посмотреть, не пустая ли там строка, и если пустая, просто вызывать list.filter() (если вызывать этот метод вообще без параметров, оно вызовет list.refresh() и все дела, а если с параметрами - делает проход с твоим колбэком сначала, а только потом рефреш)

2022-05-11 14:34 UTC, kullias commented on sources/views/settings/settingsDatatable.js
> +						this.clr();
именование очень такое c-style) не надо, это джаваскрипт. не надо экономить буквы

2022-05-11 14:34 UTC, kullias commented on sources/views/settings/settingsDatatable.js
> +		formValues.value = formValues.Value;
схема такими вещами обычно занимается ($change, $init)

2022-05-11 14:47 UTC, AlexeyXB requested changes

2022-05-11 14:47 UTC, AlexeyXB commented on sources/views/activitiesTable.js
> +		const filterTabbar = (obj) => {
Способ фильтрации в данном случае выглядит громоздко и не очень оптимальным.

2022-05-11 14:47 UTC, AlexeyXB commented on sources/views/contacts/list.js
> +		const key = [
Не самый лучший способ. Для какой-либо модификации объекта, фильтрация может работать не корректно. В данном случае т.к. у тебя идет фильтрация по всем полям, кроме Phone и StatusId, мы можем использовать Object.entries для фильтрации по ключам и после этого использовать find

2022-05-12 12:38 UTC, AlexeyXB approved these changes

2022-05-12 14:38 UTC, kullias commented on sources/views/contacts/list.js
> +					.filter(([key, value]) => (key !== "Phone" || key !== "StatusID") && typeof value === "string")
Photo забыли:
![Selection_999(877)](https://user-images.githubusercontent.com/31205423/168100923-f73cb8d3-1a06-4ed2-9973-b6ada5c4a2c4.png)
![Selection_999(878)](https://user-images.githubusercontent.com/31205423/168100949-14516bd7-1bf9-424a-8ae0-99650b0059b6.png)

2022-05-12 14:40 UTC, kullias approved these changes

2022-05-12 14:42 UTC, merged

2022-05-12 14:42 UTC, AlexeyXB commented on sources/views/contacts/list.js
> +					.filter(([key, value]) => (key !== "Phone" || key !== "StatusID") && typeof value === "string")
Поиск стал более универсальным, чем ожидалось 😄

2022-05-12 14:45 UTC, kullias commented on sources/views/contacts/list.js
> +					.filter(([key, value]) => (key !== "Phone" || key !== "StatusID") && typeof value === "string")
ну што паробіш, ладно) явно ж просто забыли, прошлый раз учитывали
шутки-шутками, а я в прошлую академию, когда тестировала первый проект, не глядя сначала в код, не могла понять, чего он все контакты показывал по букве, которой не было ни в одной строке во всех данных
она была во всех фотках!